-- document existing key chains
require('which-key').add({
  { "<A-0>",      "<Cmd>BufferLast<CR>",         desc = "Goto Last Tab" },
  { "<A-1>",      "<Cmd>BufferGoto 1<CR>",       desc = "Goto 1st Tab" },
  { "<A-2>",      "<Cmd>BufferGoto 2<CR>",       desc = "Goto 2nd Tab" },
  { "<A-3>",      "<Cmd>BufferGoto 3<CR>",       desc = "Goto 3rd Tab" },
  { "<A-4>",      "<Cmd>BufferGoto 4<CR>",       desc = "Goto 4th Tab" },
  { "<A-5>",      "<Cmd>BufferGoto 5<CR>",       desc = "Goto 5th Tab" },
  { "<A-6>",      "<Cmd>BufferGoto 6<CR>",       desc = "Goto 6th Tab" },
  { "<A-7>",      "<Cmd>BufferGoto 7<CR>",       desc = "Goto 7th Tab" },
  { "<A-8>",      "<Cmd>BufferGoto 8<CR>",       desc = "Goto 8th Tab" },
  { "<A-9>",      "<Cmd>BufferGoto 9<CR>",       desc = "Goto 9th Tab" },
  { "<A-Left>",   "<Cmd>BufferMovePrevious<CR>", desc = "Move Previous Tab" },
  { "<A-Right>",  "<Cmd>BufferMoveNext<CR>",     desc = "Move Next Tab" },
  { "<A-p>",      "<Cmd>BufferPin<CR>",          desc = "Pin Tab" },
  { "<C-h>",      "<Cmd>wincmd h<CR>",           desc = "Goto Left Window" },
  { "<C-j>",      "<Cmd>wincmd j<CR>",           desc = "Goto Up Window" },
  { "<C-k>",      "<Cmd>wincmd k<CR>",           desc = "Goto Down Window" },
  { "<C-l>",      "<Cmd>wincmd l<CR>",           desc = "Goto Right Window" },
  { "<C-n>",      "<cmd>NvimTreeFocus<cr>",      desc = "Explorer" },
  { "<C-w>",      "<Cmd>BufferClose<CR>",        desc = "Close Tab" },
  { "<S-Tab>",    "<Cmd>BufferPrevious<CR>",     desc = "Previous Tab" },
  { "<Tab>",      "<Cmd>BufferNext<CR>",         desc = "Next Tab" },
  { "<leader>c",  group = "[C]ode" },
  { "<leader>c_", hidden = true },
  { "<leader>d",  group = "[D]ebugger" },
  { "<leader>d_", hidden = true },
  { "<leader>f",  "<Cmd>Format<CR>",             desc = "Format" },
  { "<leader>g",  group = "[G]it" },
  { "<leader>g_", hidden = true },
  { "<leader>h",  group = "More git" },
  { "<leader>h_", hidden = true },
  { "<leader>r",  group = "[R]ename" },
  { "<leader>r_", hidden = true },
  { "<leader>s",  group = "[S]earch" },
  { "<leader>s_", hidden = true },
  { "<leader>w",  group = "[W]orkspace" },
  { "<leader>w_", hidden = true },
})

